-- 테이블 생성: analysis_results
create table if not exists analysis_results (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  face_type text,
  skin_age integer,
  scores jsonb,
  survey_data jsonb,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS 설정: analysis_results
alter table analysis_results enable row level security;

create policy "Users can view their own analysis results"
  on analysis_results for select
  using (auth.uid() = user_id);

create policy "Users can insert their own analysis results"
  on analysis_results for insert
  with check (auth.uid() = user_id);

-- 테이블 생성: wishlist_clinics
create table if not exists wishlist_clinics (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  hospital_id text references hospitals(id),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, hospital_id)
);

-- RLS 설정: wishlist_clinics
alter table wishlist_clinics enable row level security;

create policy "Users can view their own wishlist"
  on wishlist_clinics for select
  using (auth.uid() = user_id);

create policy "Users can insert their own wishlist"
  on wishlist_clinics for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own wishlist items"
  on wishlist_clinics for delete
  using (auth.uid() = user_id);
